:PROPERTIES:
:header-args:emacs-lisp: :tangle yes :padline no
:END:

* Custom set configurations
Variables or faces can be set by [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Customization.html][Emacs Customize interface]]. Customisation shall be set explicitly in this file. Therefore, the following code blocks should always be empty:
#+begin_example emacs-lisp
  (custom-set-variables
   ;; custom-set-variables was added by Custom.
   ;; If you edit it by hand, you could mess it up, so be careful.
   ;; Your init file should contain only one such instance.
   ;; If there is more than one, they won't work right.
   )
  (custom-set-faces
   ;; custom-set-faces was added by Custom.
   ;; If you edit it by hand, you could mess it up, so be careful.
   ;; Your init file should contain only one such instance.
   ;; If there is more than one, they won't work right.
   )
#+end_example

* Startup behaviour
Disable splash screen at startup:
#+begin_src emacs-lisp
  (setq inhibit-startup-screen t)
#+end_src

* General functionalities
Disable annoying sounds, like when hitting TAB and no completion can be found:
#+begin_src emacs-lisp
  (setq ring-bell-function 'ignore)
#+end_src

Disable tool bar:
#+begin_src emacs-lisp
  (tool-bar-mode -1)
#+end_src

Enable to show the current column number in the mode line:
#+begin_src emacs-lisp
  (setq column-number-mode t)
#+end_src

Based on the [[https://www.emacswiki.org/emacs/LineNumbers][Emacs Wiki]], enable display of line numbers in the buffer for programming modes:
#+begin_src emacs-lisp
  (add-hook 'prog-mode-hook #'display-line-numbers-mode)
#+end_src

Enable displaying of file sizes in the mode line:
#+begin_src emacs-lisp
  (setq size-indication-mode t)
#+end_src

Set language environment to German:
#+begin_src emacs-lisp
  (set-locale-environment "de_DE.utf-8")
#+end_src

* General appearance
Themes are not used. Only adjustments to the standard faces are made.

** Customise default face
Just revert foreground and background colour:
#+begin_src emacs-lisp
  (set-face-background 'default "black")
  (set-face-foreground 'default "white")
#+end_src

** Customise cursor face
Make the cursor green:
#+begin_src emacs-lisp
  (set-face-background 'cursor "green")
#+end_src

* Package management
** General package management
Define the package archives to use:
#+begin_src emacs-lisp
  (setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
			   ("nongnu" . "https://elpa.nongnu.org/nongnu/")
			   ("melpa" . "https://melpa.org/packages/")))
#+end_src

Ensure newly installed packages are downloaded and installed properly before running:
#+begin_src emacs-lisp
  (setq use-package-always-ensure t)
#+end_src

Initialise package variables
#+begin_src emacs-lisp
  (package-initialize)
#+end_src

Refresh package cache if not done yet:
#+begin_src emacs-lisp
  (unless package-archive-contents (package-refresh-contents))
#+end_src

** Use /use-package/
Install [[https://github.com/jwiegley/use-package][use-package]], if not done yet:
#+begin_src emacs-lisp
  (unless (package-installed-p 'use-package) (package-install 'use-package))
#+end_src

Initialise use-package:
#+begin_src emacs-lisp
  (eval-when-compile (require 'use-package))
#+end_src

** Add Signature management
Install [[https://elpa.gnu.org/packages/gnu-elpa-keyring-update.html][gnu-elpa-keyring-update]] to keep GPG keyring  or GNU ELPA up to date and keep the default behaviour:
#+begin_src emacs-lisp
  (use-package gnu-elpa-keyring-update
    :config  (setq package-check-signature 'allow-unsigned))
#+end_src

If gnu-elpa-keyring-update cannot be installed, because of expired signatures, the signature check can be temporary disabled, like described in the [[https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1970090.html][Debian mailing list]]:
#+begin_src emacs-lisp :tangle no
  (setq package-check-signature nil)
#+end_src

* Use /which-key/
Install and counfigure [[https://github.com/justbur/emacs-which-key][which-key]] to display current awailable key bindings while typing:
#+begin_src emacs-lisp
  (use-package which-key
    :config  (which-key-mode))
#+end_src

* Use /counsel/, /ivy/ and /swiper/
Install and configure [[https://github.com/abo-abo/swiper][counsel]] along with ivy and swiper:
#+begin_src emacs-lisp
  (use-package counsel
    :bind
    ("C-s" . swiper-isearch)
    ("C-x b" . counsel-switch-buffer)
    :config (counsel-mode))
#+end_src

Install [[https://github.com/Yevgnen/ivy-rich][ivy-rich]], to have more [[https://oremacs.com/swiper/][actions]] with ~M-o~ and better UI in the minibuffer for ivy completions:
#+begin_src emacs-lisp
  (use-package ivy-rich
    :config (ivy-rich-mode))
#+end_src

* Use /helpful/
Install [[https://github.com/Wilfred/helpful][helpful]] to enhance Emacs help with more contextual information:
#+begin_src emacs-lisp
  (use-package helpful
    :commands
    (helpful-callable
     helpful-variable
     helpful-command
     helpful-key
     helpful-at-point)
    :custom
    (counsel-describe-function-function #'helpful-callable)
    (counsel-describe-variable-function #'helpful-variable)
    :bind
    ([remap describe-function] . counsel-describe-function)
    ([remap describe-variable] . counsel-describe-variable)
    ([remap describe-command] . helpful-command)
    ([remap describe-key] . helpful-key)
    ("C-h C-x d" . helpful-at-point))
#+end_src

* Use /projectile/
Install [[https://github.com/bbatsov/projectile][projectile]]:
#+begin_src emacs-lisp
  (use-package projectile
    :config (projectile-mode)
    :bind-keymap ("C-c p" . projectile-command-map))
#+end_src

Use [[https://github.com/ericdanan/counsel-projectile][counsel-projectile]] to have integration with counsel:
#+begin_src emacs-lisp
  (use-package counsel-projectile
    :config (counsel-projectile-mode))
#+end_src

* Use /Magit/
Install [[https://magit.vc/][Magit]] to have a nice Git integration:
#+begin_src emacs-lisp
  (use-package magit)
#+end_src

* Editing modes

** Use /Org mode/
Configuration of Org mode includes several steps:

*** Agenda files
The list of agenda files is specific to different environments and user accounts. Each user account has to define its own list of files as a textfile and put it under ~/.emacs.d/org-agenda-files~, like the following example:
#+begin_example
~/Path to 1st directory/agenda file 1
~/Path to 1st directory/agenda file 2
~/Path to 2nd directory/agenda file 1
...
#+end_example
This file is read by a function and inserted into the variable ~org-agenda-files~.

*** Enable visual-line-mode
Since Org mode is for editing texts, visual line mode with word wrap is enabled:
#+begin_src emacs-lisp
  (use-package org
    :custom
    (org-agenda-files
     (with-temp-buffer (insert-file-contents
			(concat user-emacs-directory "org-agenda-files"))
		       (split-string (buffer-string) "\n" t)))
    (org-babel-load-languages
     '((emacs-lisp . t)
       (shell . t)))
    :hook (org-mode . visual-line-mode))
#+end_src

** Use /csv-mode/
Install [[https://elpa.gnu.org/packages/csv-mode.html][csv-mode]]:
#+begin_src emacs-lisp
  (use-package csv-mode)
#+end_src
